export const COACH_TIPS: string[] = [
  "Day one jitters are completely normal. Every single person on this team has been exactly where you are right now.",
  "Benefits enrollment has a deadline. Don't let it sneak past you — check the enrollment window in your onboarding materials.",
  "When in doubt, ask. No question is too small when you're still learning the ropes.",
  "AAP has been around since 1956. You're joining a long legacy of people who care deeply about independent pharmacy.",
  "The fastest way to feel settled? Learn two people's names and one thing each of them is proud of.",
  "Your time-away requests go through your manager first, then HR. Module 4 walks you through the full flow.",
  "Pharmacy is a relationship business — and so is working inside AAP. Relationships here are real currency.",
  "Reading a policy and understanding a policy are two different things. If one doesn't click, re-read it with a real scenario in mind.",
  "Progress, not perfection. Every module you complete is a real, tangible win.",
  "AAP's culture has a direct line to its mission: help independent pharmacies survive and thrive.",
  "Your manager isn't the only person you can learn from. Peers who've been here 2–3 years are often the best shortcut.",
  "If the quiz trips you up, go back and re-read the section — the answer is almost always right there.",
  "Benefits aren't just health insurance. Check the full list — there might be something that surprises you.",
  "Onboarding is a process, not a one-time event. Give yourself grace as you get settled in.",
  "The first 90 days are for learning. Nobody expects you to know everything yet.",
  "Speaking up early — even just asking a question in a meeting — helps your team see your engagement.",
  "Module completions are tracked manually here. That means each one is intentional. Yours counts.",
  "AAP's member pharmacies are small businesses with big responsibilities. That context matters in every role.",
  "HR policies exist to protect you, not just the company. Understanding them is genuinely for your benefit.",
  "A quick intro email to your team on day one can pay dividends for months down the road.",
  "Acronyms will fly around constantly. It's always okay to ask what one means — others in the room probably don't know either.",
  "One small win today is better than one big goal someday.",
  "The Employee Handbook is a reference, not light reading. Knowing where to find things matters more than memorizing it.",
  "If something in a policy doesn't make sense, ask why. Understanding the 'why' makes compliance feel a lot less like compliance.",
  "Pay attention to the little cultural cues in your first weeks. How do people greet each other? What gets celebrated?",
  "Direct deposit setup is easy, but the deadline to get your first check deposited — not mailed — is sooner than you think.",
  "Your PTO starts accruing right away. The balance might be small at first, but it's yours.",
  "If you're working remotely, making yourself visible in Slack, on calls, and in emails matters more than you might expect.",
  "Being new means you get to ask questions others are too embarrassed to ask. Use that window while it's open.",
  "Find one person who's been here 5+ years and grab coffee with them. Their perspective is worth more than any handbook.",
  "The quiz at the end of each module isn't a gotcha. It's a check-in to make sure the key ideas actually landed.",
  "When you complete a module, take a second to absorb it. You just did something real.",
  "AAP's independent pharmacy members are the reason this company exists. Keep that in mind no matter your role.",
  "Your ideas matter from day one — but so does listening first. Earn the context, then share the perspective.",
  "HR's door is open. Nicole Thornton handles everything from benefits questions to onboarding confusion. Don't guess — just ask.",
  "Mistakes in the first 90 days are learning. Hiding them is a bigger problem than making them.",
  "Spend some time exploring the AAP member-facing products. Understanding what you're supporting changes everything.",
  "The 90-day review isn't an evaluation — it's a conversation. Come with questions, not just answers.",
  "Don't compare your chapter one to someone else's chapter ten.",
  "Your first few weeks are a gift — everyone expects you to need time. Use it wisely and intentionally.",
  "The best thing you can do for your career at AAP? Show up curious every single day.",
  "Read the room before speaking up in meetings — but also know that your fresh perspective is genuinely valuable.",
  "Module acknowledgements are your digital agreement that you've read and understood the content. Take that seriously.",
  "Feeling overwhelmed is a sign you care. Take a breath, come back to the first module, and keep moving.",
  "Understanding the pharmacy industry isn't just useful for industry-specific roles — it's useful for every role at AAP.",
  "You don't have to memorize every policy. You have to know they exist and where to find them when you need them.",
  "Ask your manager what success looks like at 30, 60, and 90 days. That conversation will center you more than almost anything else.",
  "Every completed module is a signal — to yourself and to your manager — that you're taking this seriously.",
  "The learning curve in a new job is steep for everyone. The timeline is measured in months, not days.",
  "Building a good relationship with HR early makes everything easier later. True story.",
  "Your first year at any company is an investment. Trust the process — even when it feels slow.",
  "Most new hires say the thing they wish they'd done sooner was introduce themselves to more people. Don't wait.",
  "If you get stuck on a module, sleep on it. A fresh read in the morning often makes everything click.",
  "You were hired because someone believed in you before you proved yourself. Remember that on the hard days.",
  "The work you do here directly supports independent pharmacists serving real communities. That's worth something.",
  "Nobody expects you to come in knowing everything. They expect you to come in wanting to learn.",
  "Celebrate the small wins — every completed module, every quiz passed, every policy understood. They add up.",
  "When something feels confusing, write down your question. A written question is halfway to an answered one.",
  "The onboarding experience you're having right now? Someone built it specifically to help you succeed. You're not alone in this.",
  "One of the best things about being new: you see things experienced employees have stopped noticing. Share those observations.",
];
